### PR TITLE
Add some timeout and periodic status messages for the lifecycle tests

### PR DESCRIPTION
**Pull request by jeremyrickard**
@krancour i took a stab at implementing something for #289. Feel free to completely ignore it.

### CODE REVIEW

**Comment by krancour** [comment]
@jeremyrickard this looks pretty good, but I discovered we can do one better...

I had been hoping we could get the tests to spit out results _before_ we initiate and wait for cleanup. It turns out we can.

```
package main

import (
	"fmt"
	"os"
	"testing"
	"time"
)

func TestFoo(t *testing.T) {}

func TestMain(m *testing.M) {
	fmt.Println("----> starting")
	exitCode := m.Run()
	<-time.After(time.Second * 5)
	fmt.Println("----> done")
	os.Exit(exitCode)
}
```

Think you can adapt your changes to take advantage of this? (The code that initializes the tests by choosing and _creating_ a resource group also will need to move.)

Sound ok?

**Comment by krancour** [comment]
Out put from the example code int he previous comment. Note the "done" comes _after_ the test results.

```
$ go test github.com/Azure/open-service-broker-azure/foo -v
----> starting
=== RUN   TestFoo
--- PASS: TestFoo (0.00s)
PASS
----> done
ok  	github.com/Azure/open-service-broker-azure/foo	5.010s
```

**Comment by jeremyrickard** [comment]
testing.M is awesome.

**Comment by jeremyrickard** [comment]
```
--- PASS: TestServices (1186.35s)
    --- PASS: TestServices/lifecycle (0.00s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/azuresearch (100.73s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/storage/blob_storage_account (101.17s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/keyvault (101.24s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/storage/blob_storage_account_with_a_blob_container (102.73s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/storage/general_purpose_storage_account (119.88s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/mssql/new_server_and_database_(all_in_one) (175.74s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/mssql/new_server_with_database_child_test (259.70s)
            --- PASS: TestServices/lifecycle/TestServices/lifecycle/mssql/new_server_with_database_child_test/database_on_new_server (103.18s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/postgresql/all-in-one (403.68s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/servicebus (428.77s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/mysql/server_and_database_(all-in-one) (357.35s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/eventhub (368.30s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/aci (142.58s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/postgresql/dbms-only (513.99s)
            --- PASS: TestServices/lifecycle/TestServices/lifecycle/postgresql/dbms-only/database-on-existing-server (219.51s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/mysql/dbms_server_only (515.99s)
            --- PASS: TestServices/lifecycle/TestServices/lifecycle/mysql/dbms_server_only/database_on_new_server (161.83s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/cosmosdb/MongoDB (582.50s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/cosmosdb/DocumentDB (637.88s)
        --- PASS: TestServices/lifecycle/TestServices/lifecycle/rediscache (1186.35s)
PASS
2018/02/22 04:36:56 ----> deleting resource group "test-f7d38d82-a7c2-46e9-be26-121b3cc491fb"
2018/02/22 04:36:57 ----> deleted resource group "test-f7d38d82-a7c2-46e9-be26-121b3cc491fb"
ok  	github.com/Azure/open-service-broker-azure/tests/lifecycle	1190.284s
```

**Pull request merged**
