### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sarce**
Fix instance name to be consistent with the name defined in contrib/k8s/examples/postgresqldb-instance.yaml.

### CODE REVIEW

**Comment by jeremyrickard** [comment]
Thanks so much for the PR @sarce. We'll review this and get it merged today.

**Comment by krancour** [comment]
Thanks @sarce. LGTM. Deferring merge to avoid mandatory rebase on a few other larger PRs that have already made their way through CI. Will still get this merged today.

**Comment by krancour** [comment]
This PR does not require CI.

**Comment by sarce** [comment]
👍

**Pull request merged**
