### PR TITLE
Refactor storage module

### PR DESCRIPTION
**Pull request by norshtein**
This PR causes **BREAKING CHANGE** in storage module. Previous four plans are made four services:
- Previous plan `general-purpose-v2-storage-account` -> Service `azure-storage-general-purpose-v2-account`
- Previous plan `general-purpose-storage-account` -> Service `azure-storage-general-purpose-v1-account`
- Previous plan `blob-container` -> Service `azure-storage-blob`
- Previous plan `blob-storage-account` -> Service `azure-storage-blob-account`

### CODE REVIEW

**Comment by norshtein** [comment]
Close #638

**Comment by zhongyi-zhang** [comment]
I know that you want to use an unified prefix `azure-storage`. But `azure-storage-blob-account`, is it ambiguous and misleading to blob service in GP storage? Though `azure-storage-blob-storage-account` is verbose in the word `storage`, I think it is still better here.

**Comment by norshtein** [comment]
How about  `azure-storage-general-purpose-v2-storage-account`, `azure-storage-general-purpose-v1-storage-account`, `azure-storage-blob-storage-account-and-container`, `azure-storage-blob-storage-account` ?

**Comment by zhongyi-zhang** [comment]
Looks good.

**Comment by norshtein** [comment]
Also made `azure-storage-blob-storage-account` as a parent service and make the name of the container in `azure-storage-blob-storage-account-and-container` configurable. Please have a review.

**Pull request merged**
