### PR TITLE
Add metadata for service classes and plans

### PR DESCRIPTION
**Pull request by sozercan**
Adds service classes and plans metadata for displaying DisplayName, ImageUrl, LongDescription, DocumentationUrl and SupportUrl

### CODE REVIEW

**Comment by jeremyrickard** [comment]
@sozercan there were some lint issues on this. Could you amend this PR with lint fixes?

**Comment by sozercan** [comment]
@jeremyrickard thanks, added nolint on metadata and urls

**Comment by jeremyrickard** [comment]
@sozercan we've had some churn in master and there is a conflict on pkg/service/catalog.go now. If you have time and could resolve that, it would be appreciated :) Let me know if not and I'll handle it.

**Comment by jeremyrickard** [comment]
LGTM, pending CII

**Comment by jeremyrickard** [comment]
Thanks @sozercan

**Comment by krancour** [comment]
Thanks @sozercan !

**Pull request merged**
