### PR TITLE
Handle `nil` instance detail in deprovisioning

### PR DESCRIPTION
**Pull request by norshtein**
According to #563, there exists the possibility that the instance detail is `nil` when error happens in early provisioning, so we do a special judgement when creating deprovisioning step. If the instance detail is `nil`, we simply return without executing real deprovisioning function.

### CODE REVIEW

**Comment by norshtein** [comment]
So we have two possible implementations:
1. Do the judgement in http deprovision handler, an Error code should be returned when the service instance detail is `nil`, which causes the deletion of the service instance fails. 
2. Wrapping special judgement when creating deprovisioning step. In this case, the service instance can be successfully deleted(since we return `nil` as error, the broker will think the deprovisioning step succeed). 

I prefer using the second implementation. When the service instance detail is `nil`, we can guarantee no service instance is created and no resource is allocated, and it's reasonable and user-friendly to just delete this record in the PaaS platform.

**Comment by zhongyi-zhang** [comment]
@norshtein for 1# we can also deprovision successfully by just deleting the invalid instance from store and returning OK.

**Comment by norshtein** [comment]
Yes, you're right. The advantage of 1# is it's more "standard" and it might save function invoking time, and the disadvantage of 1# is that more code need to be injected to existing code. I'm OK with both implementations and I can change current implementation to 1#. Which one do you prefer @zhongyi-zhang  @jeremyrickard @krancour ?

**Comment by krancour** [comment]
I prefer option 1.

I should also say that we hadn't put a lot of thought into what it looks like to deprovision something that previously failed provisioning. (Is that even valid?) I don't have time to dig in right now, but I would strongly urge looking to the OSB spec for some clarification in how this is expected to work.

**Comment by zhongyi-zhang** [comment]
See lines above this section: https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#polling-last-operation-for-service-bindings
It specifies a "MUST" to the platform and only a "MAY" to the broker. That delegates how to handle it to the broker. With `nil` instance detail -- it must be an orphan, we can eliminate the instance in deprovision API handler level. With valid instance detail, the deprovision request is delegated to the service module. And the service module must ensure deleting all the Azure resources it created, whatever the instance state is, successful or failed.

**Comment by norshtein** [comment]
Here comes another question: what if the service instance is not `nil` but the service instance is not successfully created? Say it fails in ARM deployment, in this case, the deprovision step of this service will be executed, which will return an error for most services (since the SDK can't delete an non-existing instance). Then the service instance will go to state `delete failed`, and can never be deleted by normal operation.

**Comment by zhongyi-zhang** [comment]
@norshtein that's what the service modules should handle correctly by giving consideration to both success and failure state. Generally they can just ignore no-content deletions. Think about that: even the deprovisioning of a successful provisioning might fail, and only part of Azure resources are deleted. Then the platform retry deprovisioning, the situation would be the same as a failed provisioning.

**Comment by norshtein** [comment]
But the deprovision will always fail in my example. Currently almost no service's deprovisioning step judges whether the service instance is existing.

**Comment by zhongyi-zhang** [comment]
So they are separate issues for the service modules. Fortunately they seldom occur as Azure REST APIs are not so unstable. We can fix them later.

**Pull request merged**
