### PR TITLE
append instead of replacing user-agent

### PR DESCRIPTION
**Pull request by joshgav**
updates https://github.com/Azure/open-service-broker-azure/pull/172

### CODE REVIEW

**Comment by krancour** [comment]
Thanks @joshgav. This LGTM, but underscores some existing DRY exceptions in this code. We'll merge this PR sooner than later (pending CI) and I'll open a separate PR to fix the DRY exceptions.

Thanks!

**Comment by krancour** [comment]
There's a lint failure here. I will fix.

**Comment by krancour** [comment]
Lint failures are fixed. Holding on LGTM / merge because I think we're waiting on a definite answer re: whether our analytics can query "contains" on the user-agent string instead of querying for an exact match.

**Comment by seanmck** [comment]
Confirmed that telemetry can do regex, so we're good to go.

**Comment by joshgav** [comment]
thanks!

**Comment by jeremyrickard** [comment]
Thanks for confirming @seanmck.

**Pull request merged**
