### PR TITLE
Add titles for plans schema fields

### LINKED ISSUE #519: Missing title field in JSON schema for plans
The `title` field is missing in plan schemas fields. It's good to have it, especially if some uses front-end libraries for displaying forms from JSON schema.

I've used a few solutions for React and Angular and all of them displays title as label - for example, https://github.com/mozilla-services/react-jsonschema-form. It fallbacks to object key name, so it results in a rather ugly form:

image

I'm working right now on a pull request that introduces titles for all fields for plans.
Hope you'll like it 🙂 Cheers!

### PR DESCRIPTION
**Pull request by pkosiec**
Resolves #519.

### CODE REVIEW

**Comment by krancour** [comment]
Do not merge until conversation in #518 is resolved.

**Comment by pkosiec** [comment]
@krancour Sorry for that! I forgot to run `go fmt` after resolving conflicts + adjusting changes to latest master. Now all should be fine.

**Comment by krancour** [comment]
@pkosiec fyi I rebased this because some of your changes needed to be applied to a chunk of code that moved. I also fixed a few other spots where the new `Title` field was overlooked. The commit shows up as being co-authored by me now. In my mind-- all credit to you.

We'll get this merged today.

**Comment by pkosiec** [comment]
@krancour Thank you!

**Pull request merged**
