### PR TITLE
Fix icons

### LINKED ISSUE #666: Icons are no longer valid
Icons for the classes are pointing to https://azure.microsoft.com/svghandler/postgresql/?width=200 which doesn't seem to be valid anymore

### PR DESCRIPTION
**Pull request by zhongyi-zhang**
Fix #666.

### CODE REVIEW

**Comment by zhongyi-zhang** [comment]
Can anyone help verify the fix? @arapulido @alberttwong could you? Not quite sure if it works for you.

**Comment by alberttwong** [comment]
I used https://raw.githubusercontent.com/zhongyi-zhang/open-service-broker-azure/icon/contrib/openshift/osba-os-template.yaml and it didn't work.

**Comment by zhongyi-zhang** [comment]
Oh, sorry I shall pulish a test image for your try. That template you used installs from a certain published image. (It is microsoft/azure-service-broker:v1.0.1 as you can see.) Now it is too late in my time zone. I'll try to publish the test image tomorrow. And will be back here if done.

**Comment by zhongyi-zhang** [comment]
OSBA image publish pipeline can only be kicked after merging the PR into master. So I am using a personal repo for the test image. Please have a try if you don't mind: zzy940502/azure-service-broker:canary.

**Comment by zhongyi-zhang** [comment]
@alberttwong find this line `image: microsoft/azure-service-broker:v1.0.1` in the template you used, change to `zzy940502/azure-service-broker:canary`.

**Comment by arapulido** [comment]
With the testing image, I get the new URLs for the images correctly, but those don't render fine. For cosmosdb.svg icon, it points to this [image](https://raw.githubusercontent.com/MicrosoftDocs/azure-docs/9eb1f875f3823af85e41ebc97e31c5b7202bf419/articles/media/index/cosmosdb.svg). But that one doesn't render correctly in Firefox or Chrome.

**Comment by zhongyi-zhang** [comment]
@arapulido yeah, for direct browser opening, the xml declaration makes it only show the raw. But Github still displays it correctly: https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/media/index/cosmosdb.svg. Maybe it requires extra renderer? If so, can it be fixed in the UI provider side? Or, we can just convert the svg to png and keep them in this repo. (This is not ideal IMO :()

**Comment by arapulido** [comment]
@zhongyi-zhang that's not the reason. As you can see with this other [svg](https://landscape.cncf.io/logos/microsoft-azure.svg) the image renders correctly when opening with a browser. The problem with your images is the <xml> tag in the first line. If you remove that one, it shows correctly in the browser

**Comment by zhongyi-zhang** [comment]
Just found that appending `?sanitize=true` can do the trick. Also updated the test image. Please have another try,

**Comment by arapulido** [comment]
@zhongyi-zhang they all work well except the mysql ones, that is missing (404): https://raw.githubusercontent.com/MicrosoftDocs/azure-docs/9eb1f875f3823af85e41ebc97e31c5b7202bf419/articles/media/index/MySQL.svg?sanitize=true

**Pull request merged**
